name: Coverity CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  coverity:
    runs-on: [self-hosted, coverity]

    env:
      BRIDGE_COVERITY_PRCOMMENT_IMPACTS: High,Medium

    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Coverity Buildless Scan
        id: coverity-scan
        uses: blackduck-inc/black-duck-security-scan@v2.11.0
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}

          coverity_project_name: coverity-blackduck-scan

          coverity_stream_name: ${{ github.event_name == 'pull_request' && format('coverity-blackduck-scan-{0}', github.base_ref) || format('coverity-blackduck-scan-{0}', github.ref_name) }}

          coverity_local: true

          coverity_args: '--disable-build-command-inference --language java'

          coverity_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

          coverity_waitForScan: true